### ISSUE TITLE
example.tar.xz is just a 'tar' but not 'tar.xz'

### ISSUE THREAD

**Issue by gnilihzeux** [PSSUN/CircCode#6]
Hi, your [example.tar.xz](https://github.com/PSSUN/CircCode/blob/master/example.tar.xz) is example.tar.xz is just a 'tar' but not 'tar.xz'. Please fix it, thanks.

**Comment by PSSUN** [comment]
Jinwen,
Thank you a lot, I have fixed it.
Thanks.
