### ISSUE TITLE
Problem of pipeline

### ISSUE THREAD

**Issue by luhan125** [PSSUN/CircCode#9]
Hello,

I'm using CircCode, such a powerful tool, but I have problem, every files I used here are from your example.
When I run: python3 make_virtual_genomes.py -y config.yaml, the err is:
No. 1 length: 281
Traceback (most recent call last):
  File "make_virtual_genomes.py", line 218, in <module>
    main()
  File "make_virtual_genomes.py", line 210, in main
    info.make_genome()
  File "make_virtual_genomes.py", line 95, in make_genome
    self.genome += (circrna.seq * 2 + polyN)
TypeError: unsupported operand type(s) for *: 'Seq' and 'int'

Could you give me some advice? Thank you very much!

Best,

Lu Han

**Comment by luhan125** [comment]
Hello,

I have solved the previous problem, sorry about this. But now, I still have one problem, I don't know how to do. When I run: python3 make_virtual_genomes.py -y config.yaml, the err is:
Segmentation fault (core dumped)

Could you give me some advice? Thank you very much!

Best,

Lu Han

**Comment by PSSUN** [comment]
thank you for using CircCode,
I have never met this problem before, now I'm trying to solve this problem,
could you please show more information about your 'config.yaml' file?

**Comment by luhan125** [comment]
Hello,

Thank you for your reply. This is the content of my 'config.yaml' file:

# #######   CircCode-cofig-file   #######
# This configuration file includes all possible options and files for CircCode.
# Please input full path as well as for running all process.
# You can submit your question by submitting issue on github or sending an e-mail

# Version = 1.0
# E-mail = sps@snnu.edu.cn
# Date = 20 July 2019

# The name of genome
genome_name: virGenome

#################
# required data #
#################

# The path of genome file
genome_fasta: /xtdisk/guocx_group/wangql/luhan/testis/CircCode/CircCode/example/genome_fasta

# The path of gtf file of genome
genome_gtf: /xtdisk/guocx_group/wangql/luhan/testis/CircCode/CircCode/example/genome.gtf

# The path of ribo-seq raw reads file
raw_reads:
           - /xtdisk/guocx_group/wangql/luhan/testis/pub_data/SRA/SRR3495992.sra
# The path of ribosome sequence file
ribosome_fasta: /asnas/guocx_group/yaofw/reference/mm9/mm10/rRNA/rRNA.mm10.rfam.ensemble.fa

# The path of trimmomatic.jar
trimmomatic_jar: /xtdisk/guocx_group/wangql/luhan/testis/CircCode/CircCode/requiredSoft/trimmomatic-0.38.jar

# The path of Candidate circRNA
circrnas: /xtdisk/guocx_group/wangql/luhan/testis/CircCode/CircCode/example/circrnas

# The path of adapters file
riboseq_adapters: /xtdisk/guocx_group/wangql/luhan/testis/CircCode/CircCode/example/riboseq-adapters.fa

# Coding sequence
coding_seq: /xtdisk/guocx_group/wangql/luhan/testis/CircCode/CircCode/example/coding_seq.fa

# Non-coding sequence
non_coding_seq: /xtdisk/guocx_group/wangql/luhan/testis/CircCode/CircCode/example/non_coding_seq.fa

#####################
# Required location #
#####################

# The path of folder for storing the final result
result_file_location: /xtdisk/guocx_group/wangql/luhan/testis/CircCode/result_file_1

# The path of folder for storing temporary results
tmp_file_location: /xtdisk/guocx_group/wangql/luhan/testis/CircCode/tmp_file_1

#################
# OTHER OPTIONS #
#################

# The type of reads, please input single or pair
reads_type: single
# ribotype
ribotype: sra
# Coverage counts, DEFAULT = 10.
coverage_counts: 10

# The thread to run tophat2 and SEPCtr, DEFAULT = 6
thread: 6

# merge all the NGS data: T or F
merge: F




best,

Lu Han

**Comment by PSSUN** [comment]
In this line:
The path of genome file
genome_fasta: /xtdisk/guocx_group/wangql/luhan/testis/CircCode/CircCode/example/genome_fasta
I noted that your genome_fasta file is genome_fasta, make sure this file is in .fasta format.
Beside, could you please tell me the RAM of your computer?

**Comment by luhan125** [comment]
All the files I used are from your example. I am sure this file is in .fasta format, and I also try to change the name of this file to genome.fa, but the err is the same: Segmentation fault

**Comment by luhan125** [comment]
I used sever to do this. And the RAM I applyed was 90gb. I show it here:
#!/bin/sh
#PBS -N find
#PBS -e find.err
#PBS -o find.log
#PBS -q core40
#PBS -l mem=90gb,walltime=240:00:00,nodes=1:ppn=10
#HSCHED -s A+B+C
#PPN limit 10

**Comment by PSSUN** [comment]
Hi Lu,
I'm trying to reproduce this error and I will contact you in 2 days.

**Comment by luhan125** [comment]
OK, thank you very much!

**Comment by PSSUN** [comment]
you have to increase the stack that your operating system allocates for the python process.

The way to do it is operating system dependant. In Linux, you can check with the command ulimit -s your current value and you can increase it with `ulimit -s <new_value>`

Try doubling the previous value and continue doubling if it does not work, until you find one that does or run out of memory.

please try this command in terminal:
`ulimit -S -s unlimited`

**Comment by PSSUN** [comment]
here's another answer:
---
My recent annoyance with Python 3.7 on Windows Subsystem for Linux is that: on two machines with the same Pandas library, one gives me segmentation fault and the other reports warning. It was not clear which one was newer, but "re-installing" pandas solves the problem.

Command that I ran on the buggy machine.
`conda install pandas`
More details: I was running identical scripts (synced through Git), and both are Windows 10 machine with WSL + Anaconda. Here go the screenshots to make the case. Also, on the machine where command-line python will complain about Segmentation fault (core dumped), Jupyter lab simply restarts the kernel every single time. Worse still, no warning was given at all.

[https://stackoverflow.com/questions/10035541/what-causes-a-python-segmentation-fault](https://stackoverflow.com/questions/10035541/what-causes-a-python-segmentation-fault)
